### PR TITLE
validation for HDD sizes

### LINKED ISSUE #574: Want validation for hdd block size
On request of CPG, the new Ceres Type-2 and NCP Type-1 servers are being shipped with their hard drive block sizes set to 4k native rather than the default 512e (emulated). It has been requested that we verify the block sizes on these servers that they are indeed 4kn and raise a validation fail if any are found not to be. Corresponding issue for adding block size to the reporter is joyent/conch-livesys#112

### PR DESCRIPTION
**Pull request by karenetheridge**
This relies on the use of the 'specification' field in the hardware_product
table, specifically a section structured thusly (encoded as a json string):

    {
      disk_size => {
        <disk model> => <size in blocks>,
        ...,
        _default => <size to assume if the model is not listed here>,
      },
    }

Every device sku that needs a hard drive size validation will need this data
entered into its hardware_product.specification. Those skus that do not need
such validation need not have their data modified, and the validation will be
skipped.

closes #574.

Requires a utility to be run to add the validation to the appropriate plan before it can be used.

### CODE REVIEW

File: lib/Conch/Validation/HddSize.pm [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+
+sub validate ($self, $data) {
+    my $hw_spec = from_json($self->hardware_product_specification // {});
+
+    return if not $hw_spec->{disk_size};
+
+    foreach my $disk_serial (keys $data->{disks}->%*) {
+        my $drive_model = $data->{disks}{$disk_serial}{model};
+        if (not $drive_model) {
+            $self->fail('missing drive model for disk '.$disk_serial,
```
Comment (sungo) [inline lib/Conch/Validation/HddSize.pm]: I think we should just skip the validation if we don't have data to compare, rather than fail

Comment (karenetheridge) [reply lib/Conch/Validation/HddSize.pm]: Could do. I *think* model is a mandatory field however? (Not that our schema says it is, but my reading of the livesys code suggests that it's always there.)

Comment (sungo) [reply lib/Conch/Validation/HddSize.pm]: If we can get confirmation of that and get it into the schema or at least documentation/comments, then I'm fine with failing. 

I should also have put a similar comment in the next `->fail` as well.

Comment (perigrin) [reply lib/Conch/Validation/HddSize.pm]: If we have a disk_size in the hardware specification we are expecting to have that data in the report, if it’s not in the report something is wrong.

Comment (sungo) [reply lib/Conch/Validation/HddSize.pm]: Understood.
